version: "3.7"

services:
  php:
    image: wodby/drupal:$DRUPAL_TAG
    environment:
      PHP_FPM_CLEAR_ENV: "no"
    volumes:
    - ./docroot:/var/www/html

  crond:
    image: wodby/drupal:$DRUPAL_TAG
    environment:
      PHP_FPM_CLEAR_ENV: "no"
    volumes:
    - ./docroot:/var/www/html

  nginx:
    volumes:
    - ./docroot:/var/www/html